
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author georg
 */
public class Validation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Validation.class.getName());

    /**
     * Creates new form Validation
     */
    public Validation(){
        initComponents();
        setupLiveValidation();
    }
    
    private void setupLiveValidation(){
    addLiveCheck(txt1, this::validateName);
    addLiveCheck(id, this::validateId);
    addLiveCheck(dob, this::validateDob);
    addLiveCheck(contact, this::validateContact);
    addLiveCheck(email, this::validateEmail);

    male.addActionListener(e -> validateGender());
    female.addActionListener(e -> validateGender());
    other.addActionListener(e -> validateGender());
}

private void addLiveCheck(javax.swing.JTextField field, Runnable check){
    field.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
        public void insertUpdate(javax.swing.event.DocumentEvent e){
            check.run(); 
        }
        public void removeUpdate(javax.swing.event.DocumentEvent e){
            check.run(); 
        }
        public void changedUpdate(javax.swing.event.DocumentEvent e){
            check.run(); 
        }
    });
}

private void setStatus(javax.swing.JLabel label, boolean ok, String message){
    label.setText(message);
    label.setForeground(ok ? new java.awt.Color(0, 170, 0) : java.awt.Color.RED);
}

private boolean validateName(){
    String v = txt1.getText().trim();
    if(v.isEmpty()){
        setStatus(nameStatus, false, "Name is required"); 
        return false; 
    }
    if(v.length() < 2){
        setStatus(nameStatus, false, "At least 2 characters");
        return false;
    }
    if(!v.matches("^[a-zA-Z\\s]+$")){
        setStatus(nameStatus, false, "Letters only");
        return false;
    }
    setStatus(nameStatus, true, "Validated!");
    return true;
}

private boolean validateId(){
    String v = id.getText().trim();
    if(v.isEmpty()){
        setStatus(idStatus, false, "ID is required");
        return false;
    }
    if(!v.matches("\\d+")){ 
        setStatus(idStatus, false, "Numbers only");
        return false;
    }
    if(v.length() < 6 || v.length() > 13){
        setStatus(idStatus, false, "Only 6-13 characters");
        return false; 
    }
    setStatus(idStatus, true, "Validated!");
    return true;
}

private boolean validateDob(){
    String v = dob.getText().trim();
    try{
        java.time.LocalDate parsed;
        if(v.matches("^\\d{4}-\\d{2}-\\d{2}$")){
            parsed = java.time.LocalDate.parse(v, java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        }else if(v.matches("^\\d{2}/\\d{2}/\\d{4}$")){
            parsed = java.time.LocalDate.parse(v, java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } 
        else{
            throw new java.time.format.DateTimeParseException("Bad format", v, 0);
        }
        int year = parsed.getYear();
        if(year < 1920 || year > 2010)
        { setStatus(dobStatus, false, "Year must be 1920-2010");
        return false;
        }
        setStatus(dobStatus, true, "Validated!");
        return true;
    }catch(Exception e){
        setStatus(dobStatus, false, "Use YYYY-MM-DD");
        return false;
    }
}

private boolean validateContact(){
    String v = contact.getText().trim();
    if (!v.matches("^\\d{10}$")){
        setStatus(contactStatus, false, "Only 10 digits!");
        return false;
    }
    setStatus(contactStatus, true, "Validated!");
    return true;
}

private boolean validateEmail(){
    String v = email.getText().trim();
    if(!v.matches("^[\\w.+-]+@[\\w-]+\\.[a-zA-Z]{2,}$")){
        setStatus(emailStatus, false, "Incorrect Email");
        return false;
    }
    setStatus(emailStatus, true, "Validated!");
    return true;
}

private boolean validateGender(){
    if(!(male.isSelected() || female.isSelected() || other.isSelected())) {
        setStatus(genderStatus, false, "Please select a gender");
        return false;
    }
    String choice = male.isSelected() ? "Male" : female.isSelected() ? "Female" : "Other";
    genderStatus.setText(choice);
    genderStatus.setForeground(java.awt.Color.YELLOW);
    return true;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        ClearBtn = new javax.swing.JButton();
        ValidateBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameStatus = new javax.swing.JLabel();
        idStatus = new javax.swing.JLabel();
        dobStatus = new javax.swing.JLabel();
        genderStatus = new javax.swing.JLabel();
        contactStatus = new javax.swing.JLabel();
        emailStatus = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        Name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Name.setText("Name and Surname:");

        ID.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ID.setText("ID:");

        Date.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Date.setText("Date of Birth:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("Gender:");

        number.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        number.setText("Contact Number:");

        Address.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Address.setText("Email Address:");

        male.setText("Male");

        female.setText("Female");

        other.setText("Other");
        other.addActionListener(this::otherActionPerformed);

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(this::ClearBtnActionPerformed);

        ValidateBtn.setText("Validate");
        ValidateBtn.addActionListener(this::ValidateBtnActionPerformed);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ARACNID VALIDATION SYSTEM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        nameStatus.setText("Enter your name and your surname");

        idStatus.setText("Enter your ID");

        dobStatus.setText("Enter your date of birth");

        genderStatus.setText("pick a gender role");

        contactStatus.setText("Enter your phone number");

        emailStatus.setText("Please enter your Email");

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(this::ExitBtnActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconss/0e9bef78f2d215309fb91b2eff49e735.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(contactStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(female)
                        .addGap(18, 18, 18)
                        .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(ValidateBtn)
                        .addGap(39, 39, 39)
                        .addComponent(ClearBtn)
                        .addGap(46, 46, 46)
                        .addComponent(ExitBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(idStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(male)
                            .addComponent(female)
                            .addComponent(other))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailStatus)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ValidateBtn)
                        .addComponent(ClearBtn)
                        .addComponent(ExitBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        txt1.setText("");
        id.setText("");
        dob.setText("");
        male.setSelected(false);
        female.setSelected(false);
        other.setSelected(false);
        contact.setText("");
        email.setText("");
        nameStatus.setText(" ");
        idStatus.setText(" ");
        dobStatus.setText(" ");
        contactStatus.setText(" ");
        emailStatus.setText(" ");
        genderStatus.setText(" ");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void ValidateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidateBtnActionPerformed
        // TODO add your handling code here:
    boolean allValid = validateName() & validateId() & validateDob() & validateContact() & validateEmail() & validateGender();
    if(allValid){
        javax.swing.JOptionPane.showMessageDialog(this, "All fields are valid — saved!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

}

    // Helper method to show error dialogs
    private void showError(String message) {
    javax.swing.JOptionPane.showMessageDialog(this, message, "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    // Helper method to reset component borders back to default
    private void resetFieldBorders() {
        javax.swing.border.Border defaultBorder = javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1);
        txt1.setBorder(defaultBorder);
        id.setBorder(defaultBorder);
        dob.setBorder(defaultBorder);
        contact.setBorder(defaultBorder);
        email.setBorder(defaultBorder);
    }//GEN-LAST:event_ValidateBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int Exit = JOptionPane.showConfirmDialog(null, "Are you sure you want to leave", "Exit", JOptionPane.YES_NO_OPTION);
        if(Exit == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Validation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel Date;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JButton ValidateBtn;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel contactStatus;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel dobStatus;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailStatus;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel genderStatus;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel nameStatus;
    private javax.swing.JLabel number;
    private javax.swing.JRadioButton other;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
